### ISSUE TITLE
How to check log messages in fixture

### ISSUE THREAD

**Issue by Nikratio** [eisensheng/pytest-catchlog#37] opened 2016-03-10 22:13 UTC
[ Apologies for mis-using the issue tracker for what's essential a question, but I could not find a mailing list or other suitable forum ]

I have a large number of tests that I would like to fail if they generate log messages of warning (or higher) prioritiy. What is the best way to do that? I do not want to explicitly include `caplog` in the parameter list of every test function (and explicity check the records at the end of the function), so I thought I'd use an autouse fixture:

```
@pytest.yield_fixture(autouse=True)
def check_test_log(request, caplog):
    yield
    for record in caplog.records:
        if record.level >= logging.WARNING:
            raise AssertionError('Logger received warning messages')
```

However, this has one big and one smaller problem: 
- the small one is that the test now appears to fail in the teardown stage (e.g. pytest first reports it as passed, but then corrects itself). 
- The big problem is that it doesn't work: even if caplog captures messages, `caplog.records` is an empty list when accessed in the fixture.

Is there a better way to do this?

**Comment by abusalimov** [comment] 2016-03-24 15:51
Sorry for that late response, I missed your message for some reason. I can't say for sure, what the best option is, but AFAIK, @The-Compiler has made something similiar for one of his projects (logfail.py, IINM, I couldn't find a link though).

**Comment by The-Compiler** [comment] 2016-03-24 15:55
Yep:
- https://github.com/The-Compiler/qutebrowser/blob/master/tests/helpers/logfail.py
- https://github.com/The-Compiler/qutebrowser/blob/master/tests/helpers/test_logfail.py

Though the code to ignore log failures if `caplog.at_level` is used is rather hacky. I'll try to add the feature to catchlog once things have cooled down a bit and the current PRs are merged.

**Comment by boxed** [comment] 2018-01-15 13:42
I also had this same issue.. it was a pain to figure out what happens! The problem is that _runtest_for() sets item.catch_log_handler, overwriting that member. In the finally block it then deletes it. If you change _runtest_for to this:

```python
    @contextmanager
    def _runtest_for(self, item, when):
        """Implements the internals of pytest_runtest_xxx() hook."""
        with catching_logs(LogCaptureHandler(),
                           formatter=self.formatter) as log_handler:
            if not hasattr(item, 'catch_log_handlers'):
                item.catch_log_handlers = {}
            item.catch_log_handler = log_handler
            item.catch_log_handlers[when] = log_handler
            try:
                yield  # run test
            finally:
                del item.catch_log_handler

            if self.print_logs:
                # Add a captured log section to the report.
                log = log_handler.stream.getvalue().strip()
                item.add_report_section(when, 'log', log)
```

You can then access the logs for each of the steps (setup, call, teardown) by:

```python
caplog._item.catch_log_handlers['call']
```

You can just monkey patch that in on `LoggingPlugin._runtest_for`

**Comment by Nikratio** [comment] 2018-01-15 20:39
Here's what I ended up doing (sorry, should have reported back earlier):

```
def check_test_log(item):
   caplog = item.catch_log_handler
    for record in caplog.records:
        if (record.levelno >= logging.WARNING and
            not getattr(record, 'checklogs_ignore', False)):
            raise AssertionError('Logger received warning messages')

@pytest.hookimpl(trylast=True)
def pytest_runtest_setup(item):
    check_test_log(item)
@pytest.hookimpl(trylast=True)
def pytest_runtest_call(item):
    check_test_log(item)
@pytest.hookimpl(trylast=True)
def pytest_runtest_teardown(item, nextitem):
    check_test_log(item)
```

This also works with the catchlog functionality that has now been merged into pytest main.

**Comment by nicoddemus** [comment] 2018-01-20 13:36
FWIW pytest-dev/pytest#3117 has just been merged with a solution to this problem in pytest. 👍

**Comment by The-Compiler** [comment] 2018-01-20 15:56
I'm closing this then! 😄

**Closed as completed by The-Compiler** 2018-01-20 15:56 UTC
