### ISSUE TITLE
ArgumentError: argument --log-format: conflicting option string(s): --log-format

### ISSUE THREAD

**Issue by kierun** [eisensheng/pytest-catchlog#36] opened 2016-02-26 09:22 UTC
I am getting this exception when running my code with both py.test and pytest-catchlog. I _think_ the latter might be responsible but _I am not sure_...  Here is the trace:

```
coverage run --source junk setup.py test
running test
running egg_info
writing dependency_links to junk.egg-info/dependency_links.txt
writing junk.egg-info/PKG-INFO
writing requirements to junk.egg-info/requires.txt
writing entry points to junk.egg-info/entry_points.txt
writing top-level names to junk.egg-info/top_level.txt
reading manifest file 'junk.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'junk.egg-info/SOURCES.txt'
running build_ext
Coverage.py warning: No data was collected.
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    entry_points={'console_scripts': ['junk=junk.junk:main']})
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "setup.py", line 38, in run_tests
    errno = pytest.main(self.test_args)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 38, in main
    config = _prepareconfig(args, plugins)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 117, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/helpconfig.py", line 28, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    _reraise(*ex)  # noqa
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 852, in pytest_cmdline_parse
    self.parse(args)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 957, in parse
    self._preparse(args)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 922, in _preparse
    self.known_args_namespace = ns = self._parser.parse_known_args(args)
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 490, in parse_known_args
    return self.parse_known_and_unknown_args(args)[0]
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 496, in parse_known_and_unknown_args
    optparser = self._getparser()
  File "/home/usr/repos/junk/.tox/py27/lib/python2.7/site-packages/_pytest/config.py", line 475, in _getparser
    arggroup.add_argument(*n, **a)
  File "/usr/lib64/python2.7/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/usr/lib64/python2.7/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/usr/lib64/python2.7/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/usr/lib64/python2.7/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib64/python2.7/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
ArgumentError: argument --log-format: conflicting option string(s): --log-format
make: *** [coverage] Error 1
```

**Comment by The-Compiler** [comment] 2016-02-26 09:28
Can you try invoking pytest directly, i.e. not via `setup.py test`?

**Comment by kierun** [comment] 2016-02-26 09:32
> Can you try invoking pytest directly, i.e. not via setup.py test?

Yes.  If I invoke it either via `py.test ...` or `python setup.py tests` it works fine.  It is just when running within `tox` that I get this error.

Apologies for being unclear.

**Comment by abusalimov** [comment] 2016-02-26 11:54
Could you also post your `tox.ini`/`pytest.ini` (or whatever file providing the `[pytest]` section, m.b. `setup.cfg`) please?

**Comment by kierun** [comment] 2016-02-26 12:02
The py.test section is in `setup.cfg` and reads:

```
[pytest]
addopts = --maxfail=2 -rfEsxXw --capture=sys --color=auto
norecursedirs = *.egg* .git docs env .tox junk
```

**Comment by abusalimov** [comment] 2016-02-26 12:09
Could it be a setup.py test-command related thing? Any guesses where might the `--log-format` argument come from?

**Comment by kierun** [comment] 2016-02-26 12:15
That is is the mystery! I have no idea where that `--log-format` option comes from. Grep did not show anything. 

And it only happens when I run `tox` as running either `py.test` directly or via `python setup.py tests` does not show the problem. Hell, it could not even be related to `pytest-catchlog`!  Although, I think it might be since the last time I ran `tox` was with `pytest-capturelog` but since that project is dead, I upgraded to `pytest-catchlog`.

I could paste the whole of the `tox` verbose output if that would help...

Oh, and thank you very much!

**Comment by abusalimov** [comment] 2016-02-26 12:25
@The-Compiler could you ask guys from pytest-core/tox who might have a clue to chime in?

**Comment by The-Compiler** [comment] 2016-02-26 17:03
Is there a repo where I can reproduce this somewhere? It smells like the `pytest_addoption` hook of pytest-catchlog is executed twice?

How does your `setup.py` look?

**Comment by kierun** [comment] 2016-02-29 08:22
Sadly this is a work project, so I cannot share the whole code.

My `setup.py` is more or less standard. The only thing I have extra is this (see below) to automatically run pytest from setup.

```
class PyTest(TestCommand):
    """
    http://pytest.org/latest/goodpractises.html
    """

    def finalize_options(self):
        TestCommand.finalize_options(self)
        self.test_args = []
        self.test_suite = True

    def run_tests(self):
        # Import here, cause outside the eggs aren't loaded
        import pytest
        errno = pytest.main(self.test_args)
        sys.exit(errno)
```

**Comment by kierun** [comment] 2016-02-29 08:34
AHA!  Removing the above class (`class PyTest(TestCommand):`) and using `command = coverage run --source mead setup.py test` in the `tox.ini` file does not show the problem.

**Comment by The-Compiler** [comment] 2016-02-29 08:36
Can you try switching to [the latest code from the "good practises" page](http://pytest.org/latest/goodpractises.html#manual-integration) or using `pytest-runner` like [mentioned there](http://pytest.org/latest/goodpractises.html#integrating-with-setuptools-python-setup-py-test-pytest-runner)?

**Comment by kierun** [comment] 2016-02-29 08:50
I tried using [the second one](http://pytest.org/latest/goodpractises.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) and the problem is still there.

In addition, I get these warnings from `tox`:

```
WARNING:test command found but not installed in testenv
  cmd: /home/usr/Envs/junk/bin/pip
  env: /home/usr/repos/junk/.tox/py27
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.
```

**Comment by The-Compiler** [comment] 2016-02-29 09:17
Can you share your `tox.ini` too?

**Comment by kierun** [comment] 2016-02-29 09:19
I had some stale code in my `.tox`, and `tox -r` did the trick.  So, the new updated [best practices](http://pytest.org/latest/goodpractises.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) do work fine.

So, this does solve my problem.  If that's enough of a work around, then I am happy for this to be closed.

**Comment by The-Compiler** [comment] 2016-02-29 09:29
Yeah, I'm guessing there's a reason those best practises were updated, so I'm closing this. Thanks for the report and the investigations!

**Comment by kierun** [comment] 2016-02-29 09:30
You are welcome!  Thank you for being patient and all your hard work and help.  It is much appreciated.

**Closed as completed by The-Compiler** 2016-02-29 09:29 UTC

**Comment by markcwhitfield** [comment] 2017-07-09 15:40
Sorry to comment on a resolved issue, but just want to add an alternate cause for future folks who might end up on this issue: I ran into this same error message because I still had `pytest-capturelog` installed in my virtualenv, which of course defines the same commandline options.

**Comment by arnuschky** [comment] 2017-07-11 06:53
Same here. :)

**Comment by exhuma** [comment] 2017-10-02 12:59
FWIW, I had the same issue as @markcwhitfield 
Replacing `pytest-capturelog` with `pytest-catchlog` resolved the issue.

**Comment by liiight** [comment] 2017-11-29 15:10
thanks for sharing @markcwhitfield , just got this after upgrading to pytest 3.3.0. Maybe its worth mentioning in their changelog as i imagine it would be a common problem

**Comment by kashif** [comment] 2017-12-05 15:48
actually `pytest-catchlog` plugin has been merged into the core so uninstalling `pytest-capturelog` and `pytest-catchlog` did the trick for me
